# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 17:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0002_curriculoaluno_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculoaluno',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CurriculoAluno', to=settings.AUTH_USER_MODEL),
        ),
    ]
