# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 17:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0003_auto_20170820_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculoaluno',
            name='usuario',
        ),
    ]
