# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0004_remove_curriculoaluno_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculoaluno',
            name='serie',
            field=models.CharField(blank=True, choices=[('ensino_medio', 'ENSINO MEDIO'), ('ensino_superior', 'ENSINO SUPERIOR'), ('tecnico', 'TECNINO')], max_length=255, null=True, verbose_name='Serie'),
        ),
    ]
