# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0005_curriculoaluno_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculoaluno',
            name='objetivo',
            field=models.CharField(max_length=255, null=True, verbose_name='Objetivos'),
        ),
    ]
