# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-05 01:26
from __future__ import unicode_literals

import core.models
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=10)),
                ('nome_aluno', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='CartaDeEncaminhamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_curso', models.CharField(max_length=25)),
                ('area_curso', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Ifpi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_ifpi', models.CharField(max_length=25)),
                ('curso', models.ManyToManyField(to='core.Curso', verbose_name='lista de cursos')),
            ],
        ),
        migrations.CreateModel(
            name='OfertaDeVaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_vaga', enumfields.fields.EnumField(default='DEFAULT', enum=core.models.TipoVaga, max_length=25)),
                ('aluno', models.ManyToManyField(through='core.CartaDeEncaminhamento', to='core.Aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_final', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_responsavel', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='TermoConvenho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regras_do_convenho', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='TermoDeCompromisso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regras_do_compromisso', models.CharField(max_length=250)),
                ('remuneracao', models.FloatField()),
                ('apolice_de_seguro', models.IntegerField()),
                ('local_atuacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meus_termos_de_compromisso', to='core.Empresa')),
                ('periodo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Periodo')),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oferta_de_vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.OfertaDeVaga')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vagas_responsaveis', to='core.Responsavel')),
            ],
        ),
        migrations.AddField(
            model_name='termodecompromisso',
            name='vaga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minhas_vagas', to='core.Vaga'),
        ),
        migrations.AddField(
            model_name='curso',
            name='oferta_de_vaga',
            field=models.ManyToManyField(to='core.OfertaDeVaga', verbose_name='oferta de vagas'),
        ),
        migrations.AddField(
            model_name='cartadeencaminhamento',
            name='oferta_de_vaga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.OfertaDeVaga'),
        ),
    ]
