# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculoaluno',
            name='rg',
            field=models.IntegerField(verbose_name='RG'),
        ),
    ]
