# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 01:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0005_curriculoaluno_serie'),
        ('core', '0002_auto_20170820_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='user_curriculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_curriculo', to='aluno.CurriculoAluno'),
        ),
    ]
