# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170819_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo Usuario'),
        ),
    ]
