# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170817_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='data_inicio',
            field=models.DateField(blank=True, verbose_name='Data inicio'),
        ),
    ]
