# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170818_2128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'verbose_name': 'Aluno'},
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='username',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nome Completo'),
        ),
    ]
