# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 02:24
from __future__ import unicode_literals

import core.models
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170817_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ifpi',
            name='nome_ifpi',
        ),
        migrations.AddField(
            model_name='ifpi',
            name='descricao_campus',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ifpi',
            name='endereco',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ifpi',
            name='nome',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='ifpi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ifpi_usuario', to='core.Ifpi', verbose_name='ifpi_usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='curso',
            name='area',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='tipo_vaga',
            field=enumfields.fields.EnumField(default='default', enum=core.models.TipoVaga, max_length=255),
        ),
    ]
