# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170819_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(blank=True, choices=[('1', 'ALUNO'), ('2', 'ADMIN')], max_length=255, null=True, verbose_name='Tipo Usuario'),
        ),
    ]
