# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 01:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170818_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='username',
            field=models.CharField(default=1, max_length=30, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[\\w.@+-]+$', 32), 'O nome do user so pode conter letras, digitos ou osseguintes caracteres @/./+/-/_invalid')], verbose_name='Nome do Usuário'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome Completo'),
        ),
    ]
