# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 02:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170817_2324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ifpi',
            old_name='curso',
            new_name='cursos',
        ),
    ]
