# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 02:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170817_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ifpi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ifpi_usuario', to='core.Ifpi', verbose_name='Instituição'),
        ),
    ]
