# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170817_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ifpi',
            name='cursos',
            field=models.ManyToManyField(to='core.Curso', verbose_name='cursos_ifpi'),
        ),
    ]
