# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170817_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='quantidade',
            field=models.IntegerField(verbose_name='Numero de Bagas'),
        ),
    ]
