# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaAtuacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Area Atuacao')),
                ('area', models.CharField(max_length=255, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade de Vagas')),
                ('tipo_vaga', models.CharField(choices=[('estagio', 'ESTAGIO'), ('emprego', 'EMPREGO'), ('jovem aprendiz', 'JOVEM APRENDIZ')], max_length=255, verbose_name='Tipo Vaga')),
                ('beneficios', models.CharField(max_length=255, verbose_name='Beneficios')),
                ('requisitos', models.CharField(max_length=255, verbose_name='Requisitos')),
                ('atividades', models.CharField(max_length=255, verbose_name='Atividades')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor')),
                ('turno', models.CharField(choices=[('manha', 'MANHA'), ('tarde', 'TARDE'), ('noite', 'NOITE')], max_length=255, verbose_name='Turno Vaga')),
                ('status', models.CharField(choices=[('ativo', 'ATIVO'), ('inativo', 'INATIVO')], default='ativo', max_length=255, verbose_name='Status Vaga')),
                ('area_atuacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curso_vaga', to='vaga.AreaAtuacao')),
                ('empresa_vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_vaga', to='vaga.Empresa')),
            ],
        ),
    ]
