# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='descricao',
            field=models.CharField(blank=255, max_length=255, verbose_name='Descricao'),
        ),
    ]
