# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaga', '0002_vaga_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaga',
            name='descricao',
        ),
    ]
