# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaga', '0003_remove_vaga_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='status',
            field=models.CharField(choices=[('ativo', 'ATIVO'), ('inativo', 'INATIVO')], default=1, max_length=255, verbose_name='Status Vaga'),
            preserve_default=False,
        ),
    ]
