# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaga', '0004_vaga_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='status',
            field=models.CharField(choices=[('ativo', 'ATIVO'), ('inativo', 'INATIVO')], default='ativo', max_length=255, verbose_name='Status Vaga'),
        ),
    ]
